import { MenuItemType } from "./types";

export const menuArray: MenuItemType[] = [
  {
    name: "Pizza",
    ingredients: ["pepperoni", "mushroom", "mozzarella"],
    id: 0,
    price: 14,
    emoji: "🍕",
  },
  {
    name: "Hamburger",
    ingredients: ["beef", "cheese", "lettuce"],
    id: 1,
    price: 12,
    emoji: "🍔",
  },
  {
    name: "Beer",
    ingredients: ["grain, hops, yeast, water"],
    id: 2,
    price: 12,
    emoji: "🍺",
  },
  {
    name: "Salad",
    ingredients: ["lettuce", "tomato", "cucumber", "olive oil"],
    id: 3,
    price: 10,
    emoji: "🥗",
  },
  {
    name: "Sushi",
    ingredients: ["rice", "fish", "seaweed", "soy sauce"],
    id: 4,
    price: 18,
    emoji: "🍣",
  },
  {
    name: "Pasta",
    ingredients: ["noodles", "tomato sauce", "parmesan", "basil"],
    id: 5,
    price: 16,
    emoji: "🍝",
  },
  {
    name: "Tacos",
    ingredients: ["tortilla", "ground beef", "cheese", "lettuce"],
    id: 6,
    price: 11,
    emoji: "🌮",
  },
  {
    name: "Hot Dog",
    ingredients: ["sausage", "bun", "ketchup", "mustard"],
    id: 7,
    price: 9,
    emoji: "🌭",
  },
  {
    name: "Coffee",
    ingredients: ["coffee beans", "water", "milk"],
    id: 8,
    price: 5,
    emoji: "☕",
  },
  {
    name: "Ice Cream",
    ingredients: ["cream", "sugar", "vanilla", "chocolate"],
    id: 9,
    price: 7,
    emoji: "🍦",
  },
  {
    name: "Cheeseburger",
    ingredients: ["beef", "cheese", "bun", "pickles"],
    id: 10,
    price: 13,
    emoji: "🍔",
  },
  {
    name: "Fruit Smoothie",
    ingredients: ["banana", "strawberry", "yogurt"],
    id: 11,
    price: 8,
    emoji: "🍓",
  },
  {
    name: "Chicken Wings",
    ingredients: ["chicken", "spices", "sauce"],
    id: 12,
    price: 15,
    emoji: "🍗",
  },
  {
    name: "Onion Rings",
    ingredients: ["onions", "batter", "oil"],
    id: 13,
    price: 6,
    emoji: "🧅",
  },
  {
    name: "Cupcake",
    ingredients: ["flour", "sugar", "butter", "vanilla"],
    id: 14,
    price: 4,
    emoji: "🧁",
  },
  {
    name: "Brownie",
    ingredients: ["chocolate", "butter", "flour", "eggs"],
    id: 15,
    price: 5,
    emoji: "🍫",
  },
];
